import { TimeDisplay } from './TimeDisplay';

interface SnapshotMetadataProps {
    snapshotTime: string;
    createdAt: string;
    generatedBy: string;
    substationId: string;
}

export function SnapshotMetadata({
    snapshotTime,
    createdAt,
    generatedBy,
    substationId,
}: SnapshotMetadataProps) {
    return (
        <dl className="space-y-4">
            <div>
                <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">Snapshot Time</dt>
                <dd className="mt-1">
                    <TimeDisplay timestamp={snapshotTime} />
                </dd>
            </div>

            <div>
                <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">Created At</dt>
                <dd className="mt-1">
                    <TimeDisplay timestamp={createdAt} />
                </dd>
            </div>

            <div>
                <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">Generated By</dt>
                <dd className="mt-1 text-sm text-gray-900 dark:text-gray-100">
                    {generatedBy.replace('_', ' ')}
                </dd>
            </div>

            <div>
                <dt className="text-sm font-medium text-gray-500 dark:text-gray-400">Substation ID</dt>
                <dd className="mt-1">
                    <code className="px-2 py-0.5 bg-gray-100 dark:bg-gray-800 rounded text-sm">
                        {substationId}
                    </code>
                </dd>
            </div>
        </dl>
    );
}
