"""
NYDFS Part 500 Cybersecurity Requirements Extractor

Specialized extractor for New York Department of Financial Services
Part 500 cybersecurity regulations. Handles domain-specific patterns
for cybersecurity controls, requirements, and compliance obligations.

Source: https://www.dfs.ny.gov/industry_guidance/cybersecurity
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple
from uuid import UUID, uuid4

# Standardized path discovery via shared utility
from shared.paths import ensure_shared_importable
ensure_shared_importable()

from shared.schemas import ExtractionPayload, ObligationType, Threshold


class NYDFSExtractor:
    """
    Domain-specific extractor for NYDFS Part 500 cybersecurity regulations.

    Extracts:
    - Cybersecurity program requirements
    - Risk assessment obligations
    - Access control mandates
    - Incident response requirements
    - Third-party service provider management
    - Annual certification requirements
    """

    JURISDICTION = "US-NY"
    FRAMEWORK = "NYDFS Part 500"

    # Regulatory patterns specific to NYDFS Part 500
    OBLIGATION_PATTERNS = {
        "MUST": [
            r"shall maintain",
            r"shall designate",
            r"shall implement",
            r"shall conduct",
            r"shall require",
            r"must establish",
            r"must maintain",
            r"must implement",
            r"is required to",
        ],
        "SHOULD": [
            r"should consider",
            r"should implement",
            r"should establish",
            r"may wish to",
        ],
        "MAY": [
            r"may use",
            r"may designate",
            r"may implement",
        ],
    }

    # Section identifiers
    SECTION_PATTERN = r"(?:§\s*500\.\d+|Section\s+500\.\d+)"

    # Timeframe patterns
    TIMEFRAME_PATTERNS = [
        r"(\d+)\s*days?",
        r"(\d+)\s*hours?",
        r"(\d+)\s*years?",
        r"(\d+)\s*months?",
        r"annually",
        r"quarterly",
        r"within\s+(\d+)\s+days",
        r"as soon as possible",
    ]

    def __init__(self):
        """Initialize the NYDFS Part 500 extractor."""
        self.obligation_matchers = self._compile_patterns()

    def _compile_patterns(self) -> dict:
        """Compile regex patterns for performance."""
        return {
            obligation_type: [
                re.compile(pattern, re.IGNORECASE) for pattern in patterns
            ]
            for obligation_type, patterns in self.OBLIGATION_PATTERNS.items()
        }

    def extract_obligations(
        self,
        text: str,
        document_id: UUID,
        tenant_id: UUID,
    ) -> List[ExtractionPayload]:
        """
        Extract NYDFS Part 500 obligations from regulatory text.

        Args:
            text: Regulatory document text
            document_id: UUID of source document
            tenant_id: UUID of tenant (for multi-tenancy)

        Returns:
            List of ExtractionPayload objects representing obligations
        """
        extractions = []

        # Split into sentences for processing
        sentences = self._split_into_sentences(text)

        for idx, sentence in enumerate(sentences):
            # Skip very short sentences
            if len(sentence) < 20:
                continue

            # Identify section reference
            section = self._extract_section(sentence)

            # Determine obligation type
            obligation_type = self._classify_obligation(sentence)
            if not obligation_type:
                continue

            # Extract thresholds (timeframes, quantitative requirements)
            thresholds = self._extract_thresholds(sentence)

            # Calculate confidence score
            confidence = self._calculate_confidence(
                sentence, obligation_type, thresholds, section
            )

            # Only extract if confidence is above minimum threshold
            if confidence < 0.65:
                continue

            # Create provision hash
            provision_hash = self._generate_hash(sentence, section)

            # Build extraction payload
            subject = "covered entity"
            action = obligation_type or "must comply"
            extraction = ExtractionPayload(
                subject=subject,
                action=action,
                document_id=document_id,
                tenant_id=tenant_id,
                provision_text=sentence.strip(),
                provision_hash=provision_hash,
                obligation_type=self._map_to_obligation_enum(obligation_type),
                thresholds=thresholds,
                jurisdiction=self.JURISDICTION,
                effective_date=None,  # NYDFS Part 500 effective date is context-specific
                confidence_score=confidence,
                embedding=None,  # Will be generated by separate service
                source_offset=self._calculate_offset(text, sentence),
                source_text=sentence,
                metadata={
                    "framework": self.FRAMEWORK,
                    "section": section,
                    "extractor": "NYDFSExtractor",
                },
            )

            extractions.append(extraction)

        return extractions

    def _split_into_sentences(self, text: str) -> List[str]:
        """
        Split text into sentences, handling regulatory-specific formatting.

        Handles:
        - Section markers
        - Subsection numbering
        - Regulatory citations
        """
        # Simple sentence splitting (can be enhanced with spaCy)
        sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z(§])", text)
        return [s.strip() for s in sentences if s.strip()]

    def _extract_section(self, text: str) -> Optional[str]:
        """Extract section reference from text (e.g., § 500.15)."""
        match = re.search(self.SECTION_PATTERN, text, re.IGNORECASE)
        return match.group(0) if match else None

    def _classify_obligation(self, text: str) -> Optional[str]:
        """
        Classify the obligation type based on regulatory language.

        Returns: "MUST", "SHOULD", "MAY", or None
        """
        text_lower = text.lower()

        # Check patterns in priority order
        for obligation_type, patterns in self.obligation_matchers.items():
            for pattern in patterns:
                if pattern.search(text):
                    return obligation_type

        return None

    def _extract_thresholds(self, text: str) -> List[Threshold]:
        """
        Extract quantitative thresholds from text.

        Examples:
        - "within 72 hours"
        - "annually"
        - "at least quarterly"
        """
        thresholds = []

        # Extract timeframes
        for pattern in self.TIMEFRAME_PATTERNS:
            matches = re.finditer(pattern, text, re.IGNORECASE)
            for match in matches:
                threshold_text = match.group(0)

                # Parse numerical value if present
                num_match = re.search(r"(\d+)", threshold_text)
                if num_match:
                    value = float(num_match.group(1))

                    # Determine unit
                    if "day" in threshold_text.lower():
                        unit = "days"
                    elif "hour" in threshold_text.lower():
                        unit = "hours"
                    elif "year" in threshold_text.lower():
                        unit = "years"
                    elif "month" in threshold_text.lower():
                        unit = "months"
                    else:
                        unit = "units"

                    # Determine operator
                    if "within" in text[: match.start()].lower()[-20:]:
                        operator = "<="
                    elif "at least" in text[: match.start()].lower()[-20:]:
                        operator = ">="
                    else:
                        operator = "=="

                    thresholds.append(
                        Threshold(
                            value=value,
                            unit=unit,
                            operator=operator,
                            context=threshold_text,
                        )
                    )
                elif "annually" in threshold_text.lower():
                    thresholds.append(
                        Threshold(
                            value=1.0, unit="years", operator="==", context="annually"
                        )
                    )
                elif "quarterly" in threshold_text.lower():
                    thresholds.append(
                        Threshold(
                            value=4.0,
                            unit="per_year",
                            operator="==",
                            context="quarterly",
                        )
                    )

        return thresholds

    def _calculate_confidence(
        self,
        text: str,
        obligation_type: str,
        thresholds: List[Threshold],
        section: Optional[str],
    ) -> float:
        """
        Calculate confidence score for extraction.

        Factors:
        - Presence of clear obligation language (higher confidence)
        - Presence of section reference (higher confidence)
        - Presence of quantitative thresholds (higher confidence)
        - Text length and complexity
        """
        confidence = 0.70  # Base confidence for NYDFS content

        # Strong obligation language boosts confidence
        if obligation_type == "MUST":
            confidence += 0.15
        elif obligation_type == "SHOULD":
            confidence += 0.08

        # Section reference boosts confidence
        if section:
            confidence += 0.10

        # Quantitative thresholds boost confidence
        if thresholds:
            confidence += 0.05 * min(len(thresholds), 2)

        # Very short or very long sentences reduce confidence
        word_count = len(text.split())
        if word_count < 10 or word_count > 100:
            confidence -= 0.10

        # Ensure confidence is in valid range
        return max(0.0, min(1.0, confidence))

    def _map_to_obligation_enum(self, obligation_str: str) -> ObligationType:
        """
        Map NYDFS-specific obligation to canonical ObligationType enum.

        NYDFS Part 500 primarily involves:
        - Recordkeeping (data retention)
        - Reporting (annual certification, breach notification)
        - Conduct (security controls, access management)
        """
        text_lower = obligation_str.lower()

        # Use keyword matching to classify
        if any(kw in text_lower for kw in ["record", "log", "maintain", "retain"]):
            return ObligationType.RECORDKEEPING
        elif any(kw in text_lower for kw in ["report", "notify", "certif", "submit"]):
            return ObligationType.REPORTING
        elif any(kw in text_lower for kw in ["disclose", "provide notice"]):
            return ObligationType.DISCLOSURE
        else:
            # Default to CONDUCT for security controls, access management, etc.
            return ObligationType.CONDUCT

    def _generate_hash(self, text: str, section: Optional[str]) -> str:
        """Generate deterministic hash for provision."""
        import hashlib

        # Normalize text for hashing
        normalized = re.sub(r"\s+", " ", text.lower().strip())

        # Include section in hash for uniqueness
        hash_input = f"{section or 'NYDFS'}:{normalized}"

        return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

    def _calculate_offset(self, full_text: str, sentence: str) -> int:
        """Calculate character offset of sentence in full document."""
        try:
            return full_text.index(sentence)
        except ValueError:
            # If exact match not found, return 0
            return 0

    @staticmethod
    def get_regulatory_metadata() -> dict:
        """
        Return metadata about NYDFS Part 500 for reference.

        Useful for UI display, documentation, and reporting.
        """
        return {
            "framework": "NYDFS Part 500",
            "full_name": "Cybersecurity Requirements for Financial Services Companies",
            "jurisdiction": "US-NY (New York)",
            "authority": "New York Department of Financial Services",
            "effective_date": "2017-03-01",
            "amendments": [
                {"date": "2023-11-01", "description": "Amendment to Part 500"},
            ],
            "scope": "Financial services companies operating in New York",
            "key_requirements": [
                "Cybersecurity Program (§ 500.02)",
                "Chief Information Security Officer (§ 500.04)",
                "Risk Assessment (§ 500.09)",
                "Multi-Factor Authentication (§ 500.12)",
                "Annual Certification (§ 500.17)",
                "Incident Response Plan (§ 500.16)",
            ],
            "url": "https://www.dfs.ny.gov/industry_guidance/cybersecurity",
        }


# Example usage
if __name__ == "__main__":
    # Sample NYDFS Part 500 text
    sample_text = """
    § 500.02 Cybersecurity Program. Each Covered Entity shall maintain a cybersecurity
    program designed to protect the confidentiality, integrity and availability of the
    Covered Entity's Information Systems.

    § 500.04 Chief Information Security Officer. Each Covered Entity shall designate a
    qualified individual responsible for overseeing and implementing the Covered Entity's
    cybersecurity program and enforcing its cybersecurity policy.

    § 500.17 Notices to Superintendent. Each Covered Entity shall submit to the
    superintendent a written statement certifying that the Covered Entity is in compliance
    with the requirements set forth in this Part annually by February 15.
    """

    extractor = NYDFSExtractor()
    extractions = extractor.extract_obligations(
        text=sample_text,
        document_id=uuid4(),
        tenant_id=uuid4(),
    )

    # CLI demonstration output
    import sys

    sys.stdout.write(
        f"Extracted {len(extractions)} obligations from NYDFS Part 500 sample\n"
    )
    for ext in extractions:
        sys.stdout.write(f"\n- {ext.provision_text[:80]}...\n")
        sys.stdout.write(f"  Obligation: {ext.obligation_type.value}\n")
        sys.stdout.write(f"  Confidence: {ext.confidence_score:.2f}\n")
        sys.stdout.write(f"  Thresholds: {len(ext.thresholds)}\n")
