/**
 * Production Budget Schema
 * Standard structure for entertainment production budgets (AICP-style)
 */

// Cost code categories (industry standard)
export const COST_CODE_CATEGORIES: Record<string, string> = {
    '100': 'Above The Line (ATL)',
    '200': 'Production',
    '300': 'Camera/Grip/Electric',
    '400': 'Art Department',
    '500': 'Post Production',
    '600': 'General Expenses',
    '700': 'Insurance & Legal',
    '800': 'Talent/Cast',
    '900': 'Miscellaneous',
};

// Unit types for line items
export type UnitType = 'day' | 'week' | 'flat' | 'hour' | 'allow' | 'kit' | 'each' | 'run';

// Worker classification
export type WorkerClassification = '1099' | 'W-2' | 'loan-out' | 'corp-to-corp';

// Deal memo status
export type DealMemoStatus = 'need_to_send' | 'sent' | 'signed' | 'complete' | 'not_required';

/**
 * Individual line item in a budget
 */
export interface BudgetLineItem {
    id: string;
    costCode: string;           // e.g., "201", "301.1"
    category: string;           // Derived from first digit
    description: string;        // Line item name
    quantity: number;           // Qty
    units: UnitType;            // Day/Flat/Hour/etc
    rate: number;               // Per-unit rate
    extension: number;          // Qty × Rate (calculated)

    // Optional metadata
    vendor?: string;
    classification?: WorkerClassification;
    dealMemoStatus?: DealMemoStatus;
    notes?: string;

    // Validation flags
    warnings: BudgetWarning[];
    errors: BudgetError[];
}

/**
 * Department/Section grouping
 */
export interface BudgetDepartment {
    code: string;               // "100", "200", etc.
    name: string;               // "Production", "Camera", etc.
    lineItems: BudgetLineItem[];
    subtotal: number;
    fringes?: number;           // If applicable
}

/**
 * Top-level budget structure
 */
export interface ProductionBudget {
    // Metadata
    projectName: string;
    projectCode?: string;
    version?: string;
    date?: Date;
    preparedBy?: string;

    // Financial summary
    departments: BudgetDepartment[];
    subtotal: number;           // Before contingency/fringes
    contingency: number;        // Usually 10%
    contingencyPercent: number; // Actual calculated %
    fringesTotal: number;       // P&W, taxes, etc.
    grandTotal: number;

    // Analysis results
    analysis?: BudgetAnalysis;
}

/**
 * Warning generated by rules engine
 */
export interface BudgetWarning {
    code: string;               // e.g., "UNION_RATE_LOW"
    severity: 'info' | 'warning' | 'critical';
    category: 'compliance' | 'optimization' | 'tax' | 'paperwork';
    lineItemId?: string;
    message: string;
    recommendation?: string;
    resourceUrl?: string;       // Link to more info
}

/**
 * Error that blocks processing
 */
export interface BudgetError {
    code: string;
    lineItemId?: string;
    message: string;
}

/**
 * Full budget analysis output
 */
export interface BudgetAnalysis {
    // Summary
    timestamp: Date;
    totalWarnings: number;
    totalErrors: number;
    riskScore: number;          // 0-100, higher = more issues

    // Categorized findings
    complianceIssues: BudgetWarning[];
    optimizationOpportunities: BudgetWarning[];
    taxCreditEligibility: TaxCreditCheck[];
    closeoutChecklist: CloseoutItem[];

    // Estimated savings/exposure
    potentialSavings: number;
    potentialExposure: number;
}

/**
 * Tax credit eligibility check
 */
export interface TaxCreditCheck {
    jurisdiction: string;       // "CA", "GA", "NM", etc.
    programName: string;        // "California Film & TV Tax Credit"
    eligible: boolean | 'maybe';
    reason: string;
    qualifiedSpend?: number;
    estimatedCredit?: number;
    requirements: string[];
    contactUrl?: string;
    filmCommissionPhone?: string;
}

/**
 * Closeout checklist item
 */
export interface CloseoutItem {
    category: 'paperwork' | 'vendor' | 'compliance' | 'deliverable';
    item: string;
    status: 'complete' | 'incomplete' | 'pending' | 'not_applicable';
    assignedTo?: string;
    dueDate?: Date;
    notes?: string;
}

// Column name aliases for parsing flexibility
export const COLUMN_ALIASES: Record<string, string[]> = {
    'costCode': ['cost_code', 'code', 'acct', 'account', 'line', 'item_no', 'item_number'],
    'description': ['description', 'desc', 'item', 'name', 'line_item', 'detail', 'category'],
    'quantity': ['qty', 'quantity', 'units', 'days', 'weeks', 'hours', 'amount'],
    'units': ['unit', 'units', 'type', 'unit_type', 'per'],
    'rate': ['rate', 'price', 'cost', 'daily_rate', 'weekly_rate', 'amount', 'per_unit'],
    'extension': ['extension', 'ext', 'total', 'subtotal', 'line_total', 'extended', 'budget'],
    'vendor': ['vendor', 'payee', 'company', 'supplier', 'source'],
    'classification': ['classification', 'class', 'type', 'worker_type', '1099_w2', 'employment_type'],
    'dealMemoStatus': ['deal_memo', 'dealmemo', 'dm_status', 'memo_status', 'deal_status', 'status'],
    'notes': ['notes', 'note', 'comments', 'memo', 'remarks'],
};

// Union rate minimums (2024 rates)
// Sources: Guild websites, rate cards, and industry standards
export const UNION_RATE_MINIMUMS: Record<string, number> = {
    // ========================================
    // SAG-AFTRA (Theatrical/TV Day Rates)
    // ========================================
    'principal': 1082,
    'day_player': 1082,
    'weekly_player': 3756,
    'background': 216,
    'stand_in': 253,
    'photo_double': 253,
    'stunt_performer': 1082,
    'stunt_coordinator': 1500,

    // ========================================
    // DGA (Directors Guild of America)
    // ========================================
    'director_theatrical': 19143,  // Weekly minimum (low budget)
    'director_tv': 25685,          // Weekly (network prime time)
    'director_streaming': 22878,   // Weekly (SVOD)
    'first_ad': 5847,              // Weekly
    'second_ad': 4237,             // Weekly
    'upm': 5847,                   // Weekly (unit production manager)
    'key_second_ad': 4584,         // Weekly

    // ========================================
    // WGA (Writers Guild of America)
    // ========================================
    'screenwriter_original': 78702,   // Original screenplay (high budget)
    'screenwriter_lowbudget': 51686,  // Low budget original
    'tv_writer_story': 28826,         // Story only (network prime)
    'tv_writer_teleplay': 43233,      // Teleplay only
    'tv_writer_both': 57656,          // Story + teleplay
    'staff_writer_weekly': 5373,      // Weekly rate
    'story_editor_weekly': 7282,      // Weekly

    // ========================================
    // IATSE Local 600 (Camera)
    // ========================================
    'dp': 850,
    'camera_operator': 650,
    'first_ac': 475,
    'second_ac': 350,
    'dit': 550,
    'loader': 325,
    'still_photographer': 575,

    // ========================================
    // IATSE Local 728 (Lighting)
    // ========================================
    'gaffer': 550,
    'best_boy_electric': 475,
    'electrician': 375,
    'rigging_gaffer': 575,
    'board_operator': 400,
    'generator_operator': 425,

    // ========================================
    // IATSE Local 80 (Grip)
    // ========================================
    'key_grip': 550,
    'best_boy_grip': 475,
    'grip': 375,
    'dolly_grip': 400,
    'rigging_grip': 400,
    'crane_operator': 475,

    // ========================================
    // IATSE Local 44 (Props)
    // ========================================
    'prop_master': 475,
    'assistant_prop_master': 400,
    'prop_maker': 375,

    // ========================================
    // IATSE Local 705 (Costume)
    // ========================================
    'costume_designer': 650,
    'costume_supervisor': 475,
    'costumer': 375,
    'key_costumer': 425,

    // ========================================
    // IATSE Local 706 (Makeup/Hair)
    // ========================================
    'makeup_dept_head': 550,
    'key_makeup': 475,
    'makeup_artist': 400,
    'hair_dept_head': 550,
    'key_hair': 475,
    'hairstylist': 400,

    // ========================================
    // IATSE Local 871 (Script Supervisors)
    // ========================================
    'script_supervisor': 475,
    'production_coordinator': 400,
    'assistant_production_coordinator': 325,

    // ========================================
    // IATSE Local 700 (Editorial)
    // ========================================
    'editor': 575,
    'assistant_editor': 400,
    'post_supervisor': 525,

    // ========================================
    // IATSE Local 695 (Sound)
    // ========================================
    'production_sound_mixer': 650,
    'boom_operator': 450,
    'sound_utility': 350,

    // ========================================
    // Teamsters Local 399 (Transportation)
    // ========================================
    'transportation_coordinator': 550,
    'transportation_captain': 475,
    'driver': 375,
    'picture_car_coordinator': 450,

    // ========================================
    // Teamsters Local 399 (Locations)
    // ========================================
    'location_manager': 575,
    'assistant_location_manager': 425,
    'location_scout': 350,

    // ========================================
    // Non-Union Minimums (CA based)
    // ========================================
    'production_assistant': 200,
    'coordinator': 350,
    'office_pa': 175,
    'set_pa': 200,
};

// Position keywords for classification
export const POSITION_KEYWORDS: Record<string, string[]> = {
    // SAG-AFTRA
    'principal': ['principal', 'lead', 'star', 'series regular'],
    'day_player': ['day player', 'guest star', 'guest', 'co-star'],
    'background': ['background', 'extra', 'bg', 'atmosphere', 'featured extra'],
    'stunt_performer': ['stunt', 'stunt performer', 'stuntman', 'stuntwoman'],
    'stunt_coordinator': ['stunt coordinator', 'stunt coord'],
    'stand_in': ['stand-in', 'stand in', 'standin'],

    // DGA
    'director_theatrical': ['director', 'feature director'],
    'director_tv': ['director', 'episodic director', 'tv director'],
    'first_ad': ['1st ad', 'first ad', 'first assistant director', '1st assistant director'],
    'second_ad': ['2nd ad', 'second ad', 'second assistant director', '2nd assistant director'],
    'upm': ['upm', 'unit production manager', 'line producer'],
    'key_second_ad': ['key 2nd', 'key second', 'key 2nd ad'],

    // WGA
    'screenwriter_original': ['writer', 'screenwriter', 'screenplay by'],
    'tv_writer_story': ['staff writer', 'story by'],
    'story_editor_weekly': ['story editor', 'executive story editor'],

    // Camera
    'dp': ['dp', 'director of photography', 'cinematographer', 'dop'],
    'camera_operator': ['camera operator', 'camera op', 'operator', 'a camera', 'b camera'],
    'first_ac': ['1st ac', 'first ac', 'first assistant camera', 'focus puller'],
    'second_ac': ['2nd ac', 'second ac', 'second assistant camera', 'clapper loader'],
    'dit': ['dit', 'digital imaging tech', 'digital imaging technician'],
    'loader': ['loader', 'film loader'],
    'still_photographer': ['still photographer', 'unit photographer', 'stills'],

    // Lighting
    'gaffer': ['gaffer', 'chief lighting technician', 'chief lt'],
    'best_boy_electric': ['best boy electric', 'bbe', 'best boy e', 'bb electric'],
    'electrician': ['electrician', 'electric', 'lamp op', 'lamp operator'],
    'rigging_gaffer': ['rigging gaffer', 'rigging electric'],
    'generator_operator': ['genny op', 'generator operator', 'genny'],

    // Grip
    'key_grip': ['key grip'],
    'best_boy_grip': ['best boy grip', 'bbg', 'best boy g', 'bb grip'],
    'grip': ['grip', 'company grip', 'set grip'],
    'dolly_grip': ['dolly grip', 'dolly'],
    'crane_operator': ['crane operator', 'technocrane', 'crane tech'],

    // Art/Props
    'prop_master': ['prop master', 'property master', 'props'],
    'assistant_prop_master': ['assistant prop', 'asst prop'],

    // Costume
    'costume_designer': ['costume designer', 'cd'],
    'costume_supervisor': ['costume supervisor', 'wardrobe supervisor'],
    'costumer': ['costumer', 'wardrobe', 'set costumer'],

    // Makeup/Hair
    'makeup_dept_head': ['makeup department head', 'key makeup', 'makeup head'],
    'makeup_artist': ['makeup artist', 'makeup', 'mua'],
    'hair_dept_head': ['hair department head', 'hair head'],
    'hairstylist': ['hairstylist', 'hair stylist', 'hair'],

    // Script/Coordination
    'script_supervisor': ['script supervisor', 'scripty', 'continuity'],
    'production_coordinator': ['poc', 'production coordinator', 'coordinator'],
    'assistant_production_coordinator': ['apoc', 'assistant coordinator'],

    // Editorial
    'editor': ['editor', 'picture editor', 'film editor'],
    'assistant_editor': ['assistant editor', 'ae', 'asst editor'],
    'post_supervisor': ['post supervisor', 'post production supervisor'],

    // Sound
    'production_sound_mixer': ['sound mixer', 'production sound', 'mixer'],
    'boom_operator': ['boom op', 'boom operator', 'boom'],
    'sound_utility': ['sound utility', 'cable person', 'third'],

    // Transportation
    'transportation_coordinator': ['transportation coordinator', 'transpo coord'],
    'transportation_captain': ['transpo captain', 'transportation captain'],
    'driver': ['driver', 'teamster driver', 'picture car driver'],

    // Locations
    'location_manager': ['location manager', 'lm'],
    'assistant_location_manager': ['alm', 'assistant location manager', 'asst lm'],
    'location_scout': ['location scout', 'scout'],

    // General
    'production_assistant': ['pa', 'production assistant', 'set pa', 'office pa'],
};

