apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scheduler-service
  labels:
    app: scheduler
spec:
  podSelector:
    matchLabels:
      app: scheduler
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: admin
      ports:
        - protocol: TCP
          port: 8600
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 5432
    - to: []
      ports:
        - protocol: TCP
          port: 6379
    - to: []
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9644
    - to:
        - podSelector:
            matchLabels:
              app: ingestion
        - podSelector:
            matchLabels:
              app: compliance
      ports:
        - protocol: TCP
          port: 8000
    - to: []
      ports:
        - protocol: TCP
          port: 443
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
