-- Migration V1: Init Schema
-- Generated by Antigravity to restore missing base schema

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- API Keys Table
CREATE TABLE IF NOT EXISTS api_keys (
    id SERIAL PRIMARY KEY,
    key_id VARCHAR(64) UNIQUE NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    key_prefix VARCHAR(12) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    tenant_id UUID, -- Using UUID to match modern standard
    billing_tier VARCHAR(50),
    allowed_jurisdictions TEXT[],
    scopes TEXT[],
    rate_limit_per_minute INTEGER DEFAULT 60,
    rate_limit_per_hour INTEGER DEFAULT 1000,
    rate_limit_per_day INTEGER DEFAULT 10000,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_by VARCHAR(36),
    revoked_by VARCHAR(36),
    revoke_reason TEXT,
    extra_data JSONB DEFAULT '{}',
    total_requests INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_api_keys_key_id ON api_keys(key_id);
CREATE INDEX IF NOT EXISTS ix_api_keys_key_hash ON api_keys(key_hash);
CREATE INDEX IF NOT EXISTS ix_api_keys_tenant_enabled ON api_keys(tenant_id, enabled);

-- Other tables referenced in V3 (Placeholders to prevent errors, optional)
-- assessment_results
-- tenant_overrides
-- customer_configs
