#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# backup_neo4j.sh — Export Neo4j graph data to Cypher dump files
#
# Since Neo4j Community Edition doesn't support online backup, this script
# exports all nodes and relationships as Cypher statements using APOC
# procedures, then compresses and stores the dump.
#
# Requirements:
#   - NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD env vars
#   - Neo4j APOC plugin installed (standard in most deployments)
#   - Python 3 with neo4j driver
#
# Usage:
#   ./scripts/backup_neo4j.sh                    # writes to ./backups/neo4j/
#   BACKUP_DIR=/mnt/backups ./scripts/backup_neo4j.sh
#
# Schedule via APScheduler, cron, or Railway cron job.
# ---------------------------------------------------------------------------
set -euo pipefail

BACKUP_DIR="${BACKUP_DIR:-./backups/neo4j}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DUMP_FILE="${BACKUP_DIR}/neo4j_dump_${TIMESTAMP}.cypher"
COMPRESSED_FILE="${DUMP_FILE}.gz"

# Ensure backup directory exists
mkdir -p "${BACKUP_DIR}"

echo "==> Starting Neo4j backup at ${TIMESTAMP}..."

python3 -c "
import os
import sys
from neo4j import GraphDatabase

uri = os.environ.get('NEO4J_URI', 'bolt://localhost:7687')
user = os.environ.get('NEO4J_USER', 'neo4j')
password = os.environ.get('NEO4J_PASSWORD', '')

if not password:
    print('ERROR: NEO4J_PASSWORD not set', file=sys.stderr)
    sys.exit(1)

driver = GraphDatabase.driver(uri, auth=(user, password))

dump_file = '${DUMP_FILE}'
node_count = 0
rel_count = 0

with driver.session() as session, open(dump_file, 'w') as f:
    f.write('// Neo4j backup: ${TIMESTAMP}\n')
    f.write('// Generated by scripts/backup_neo4j.sh\n\n')

    # Export all nodes
    f.write('// === NODES ===\n')
    result = session.run(
        'MATCH (n) '
        'RETURN labels(n) AS labels, properties(n) AS props, elementId(n) AS eid'
    )
    for record in result:
        labels = ':'.join(record['labels'])
        props = record['props']
        eid = record['eid']
        # Escape string values
        prop_parts = []
        for k, v in props.items():
            if isinstance(v, str):
                escaped = v.replace(\"'\", \"\\\\'\")
                prop_parts.append(f\"{k}: '{escaped}'\")
            elif v is None:
                continue
            else:
                prop_parts.append(f'{k}: {v}')
        props_str = ', '.join(prop_parts)
        f.write(f'CREATE (:{labels} {{{props_str}}});\n')
        node_count += 1

    # Export all relationships
    f.write('\n// === RELATIONSHIPS ===\n')
    result = session.run(
        'MATCH (a)-[r]->(b) '
        'RETURN labels(a) AS a_labels, properties(a) AS a_props, '
        '       type(r) AS r_type, properties(r) AS r_props, '
        '       labels(b) AS b_labels, properties(b) AS b_props'
    )
    for record in result:
        r_type = record['r_type']
        # Use a unique property to MATCH nodes (prefer 'id' or 'gln')
        a_props = record['a_props']
        b_props = record['b_props']
        r_props = record['r_props']

        def match_clause(labels, props):
            label_str = ':'.join(labels)
            # Try to find a unique identifier
            for key in ['id', 'gln', 'lot_code', 'name', 'uid']:
                if key in props:
                    val = props[key]
                    if isinstance(val, str):
                        val = val.replace(\"'\", \"\\\\'\")
                        return f\"(:{label_str} {{{key}: '{val}'}})\"
                    return f'(:{label_str} {{{key}: {val}}})'
            # Fallback: use all props
            parts = []
            for k, v in list(props.items())[:3]:
                if isinstance(v, str):
                    v = v.replace(\"'\", \"\\\\'\")
                    parts.append(f\"{k}: '{v}'\")
                elif v is not None:
                    parts.append(f'{k}: {v}')
            return f\"(:{label_str} {{{', '.join(parts)}}})\"

        a_clause = match_clause(record['a_labels'], a_props)
        b_clause = match_clause(record['b_labels'], b_props)

        r_prop_parts = []
        for k, v in r_props.items():
            if isinstance(v, str):
                v = v.replace(\"'\", \"\\\\'\")
                r_prop_parts.append(f\"{k}: '{v}'\")
            elif v is not None:
                r_prop_parts.append(f'{k}: {v}')
        r_props_str = ', '.join(r_prop_parts)
        r_props_clause = f' {{{r_props_str}}}' if r_props_str else ''

        f.write(
            f'MATCH (a{a_clause.replace(\"(\", \"\").replace(\")\", \"\")}), '
            f'(b{b_clause.replace(\"(\", \"\").replace(\")\", \"\")}) '
            f'CREATE (a)-[:{r_type}{r_props_clause}]->(b);\n'
        )
        rel_count += 1

driver.close()
print(f'Exported {node_count} nodes and {rel_count} relationships to {dump_file}')
"

# Compress
echo "==> Compressing backup..."
gzip "${DUMP_FILE}"

# Cleanup old backups (keep last 7)
echo "==> Cleaning up old backups (keeping last 7)..."
ls -t "${BACKUP_DIR}"/neo4j_dump_*.cypher.gz 2>/dev/null | tail -n +8 | xargs rm -f 2>/dev/null || true

echo "==> Backup complete: ${COMPRESSED_FILE}"
echo "    Size: $(du -h "${COMPRESSED_FILE}" | cut -f1)"
