
import os
import hashlib
import psycopg2
from datetime import datetime, timezone

# Config
DB_URL = os.environ.get("ADMIN_DATABASE_URL", "postgresql://regengine:regengine@localhost:5433/regengine_admin")
KEY_ID = "rge_phase2b"
SECRET = "testsecret123"
RAW_KEY = f"{KEY_ID}.{SECRET}"

def hash_key(raw_key):
    return hashlib.sha256(raw_key.encode()).hexdigest()

def seed_key():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    
    key_hash = hash_key(RAW_KEY)
    key_prefix = RAW_KEY[:12]
    now = datetime.now(timezone.utc)
    
    print(f"Seeding API Key: {RAW_KEY}")
    print(f"Hash: {key_hash}")
    
    tenant_id = "11111111-1111-1111-1111-111111111111"
    
    try:
        # Ensure tenant exists (Always run this check)
        cur.execute("SELECT id FROM tenants WHERE id = %s", (tenant_id,))
        if not cur.fetchone():
            print("Seeding tenant...")
            cur.execute("""
                INSERT INTO tenants (id, name, slug, status, settings, created_at, updated_at)
                VALUES (%s, 'Phase 2b Test Tenant', 'phase-2b-test', 'active', '{}', %s, %s)
            """, (tenant_id, now, now))
            
        # Check if exists
        cur.execute("SELECT id FROM api_keys WHERE key_id = %s", (KEY_ID,))
        if cur.fetchone():
            print("Key already exists. Updating...")
            cur.execute("""
                UPDATE api_keys 
                SET key_hash = %s, enabled = true, updated_at = %s,
                    allowed_jurisdictions = ARRAY['US'], scopes = ARRAY['read', 'write']
                WHERE key_id = %s
            """, (key_hash, now, KEY_ID))
        else:
            print("Inserting new key...")
            
            cur.execute("""
                INSERT INTO api_keys (
                    key_id, key_hash, key_prefix, name, description, 
                    tenant_id, billing_tier, enabled, created_at, 
                    rate_limit_per_minute, rate_limit_per_hour, rate_limit_per_day,
                    allowed_jurisdictions, scopes
                ) VALUES (
                    %s, %s, %s, %s, %s, 
                    %s, 'ENTERPRISE', true, %s,
                    1000, 10000, 100000,
                    ARRAY['US'], ARRAY['read', 'write']
                )
            """, (
                KEY_ID, key_hash, key_prefix, "Phase 2b Test Key", "Generated by automated audit",
                tenant_id, now
            ))
        
        conn.commit()
        print("✅ Key seeded successfully.")
        
    except Exception as e:
        conn.rollback()
        print(f"❌ Failed to seed key: {e}")
        raise
    finally:
        cur.close()
        conn.close()

if __name__ == "__main__":
    seed_key()
