'use client';

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useQuery } from '@tanstack/react-query';
import { Database, Shield, Link2 } from 'lucide-react';

interface SnapshotDetailModalProps {
    snapshotId: string;
    onClose: () => void;
}

interface SnapshotDetail {
    id: string;
    created_at: string;
    snapshot_time: string;
    substation_id: string;
    facility_name: string;
    system_status: string;
    content_hash: string;
    signature_hash: string;
    previous_snapshot_id: string | null;
    generated_by: string;
    trigger_event: string | null;
    regulatory_version: string;
    asset_states?: Record<string, Record<string, unknown>>;
    esp_config?: Record<string, unknown>;
}

function DataItem({ label, value }: { label: string; value: string | number }) {
    return (
        <div className="flex flex-col space-y-1">
            <span className="text-xs text-muted-foreground uppercase">{label}</span>
            <span className="text-sm font-medium">{value}</span>
        </div>
    );
}

function CryptoField({ label, value, link }: { label: string; value: string; link?: string }) {
    return (
        <div className="space-y-2">
            <div className="flex items-center gap-2">
                <Shield className="h-4 w-4 text-green-600" />
                <span className="text-sm font-medium">{label}</span>
            </div>
            <div className="bg-muted p-3 rounded-md">
                <code className="text-xs font-mono break-all">{value}</code>
            </div>
            {link && (
                <a href={link} className="text-xs text-primary hover:underline flex items-center gap-1">
                    <Link2 className="h-3 w-3" />
                    View previous snapshot
                </a>
            )}
        </div>
    );
}

export function SnapshotDetailModal({ snapshotId, onClose }: SnapshotDetailModalProps) {
    const { data, isLoading } = useQuery<SnapshotDetail>({
        queryKey: ['snapshot-detail', snapshotId],
        queryFn: async () => {
            const response = await fetch(
                `/api/energy/snapshots/${snapshotId}?include_asset_details=true&include_esp_config=true`
            );
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            return response.json();
        },
        enabled: Boolean(snapshotId),
    });

    return (
        <Dialog open onOpenChange={onClose}>
            <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <Database className="h-5 w-5" />
                        Snapshot Details
                    </DialogTitle>
                </DialogHeader>

                {isLoading ? (
                    <div className="space-y-4">
                        <Skeleton className="h-32 w-full" />
                        <Skeleton className="h-32 w-full" />
                        <Skeleton className="h-32 w-full" />
                    </div>
                ) : data ? (
                    <Tabs defaultValue="overview" className="w-full">
                        <TabsList className="grid w-full grid-cols-3">
                            <TabsTrigger value="overview">Overview</TabsTrigger>
                            <TabsTrigger value="assets">Assets</TabsTrigger>
                            <TabsTrigger value="crypto">Cryptographic Proof</TabsTrigger>
                        </TabsList>

                        <TabsContent value="overview" className="space-y-6">
                            <div className="grid grid-cols-2 gap-6">
                                <DataItem label="Snapshot ID" value={data.id} />
                                <DataItem
                                    label="Timestamp"
                                    value={new Date(data.snapshot_time).toLocaleString()}
                                />
                                <DataItem label="Facility" value={data.facility_name} />
                                <DataItem label="Substation ID" value={data.substation_id} />
                                <div className="flex flex-col space-y-1">
                                    <span className="text-xs text-muted-foreground uppercase">System Status</span>
                                    <Badge variant={data.system_status === 'NOMINAL' ? 'default' : 'destructive'}>
                                        {data.system_status}
                                    </Badge>
                                </div>
                                <DataItem label="Generated By" value={data.generated_by} />
                                {data.trigger_event && (
                                    <DataItem label="Trigger Event" value={data.trigger_event} />
                                )}
                                <DataItem label="Regulatory Version" value={data.regulatory_version} />
                            </div>
                        </TabsContent>

                        <TabsContent value="assets" className="space-y-4">
                            {data.asset_states && Object.keys(data.asset_states).length > 0 ? (
                                <div className="border rounded-lg overflow-hidden">
                                    <table className="w-full text-sm">
                                        <thead className="bg-muted">
                                            <tr>
                                                <th className="p-3 text-left font-medium">Asset ID</th>
                                                <th className="p-3 text-left font-medium">Status</th>
                                                <th className="p-3 text-left font-medium">Details</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {Object.entries(data.asset_states).map(([assetId, state]: [string, Record<string, unknown>]) => (
                                                <tr key={assetId} className="border-t">
                                                    <td className="p-3 font-mono text-xs">{assetId}</td>
                                                    <td className="p-3">
                                                        <Badge variant="outline">{String(state.status || 'N/A')}</Badge>
                                                    </td>
                                                    <td className="p-3 text-xs text-muted-foreground">
                                                        {JSON.stringify(state, null, 2).slice(0, 100)}...
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            ) : (
                                <div className="text-center py-12 text-muted-foreground">
                                    <Database className="h-12 w-12 mx-auto mb-4 opacity-50" />
                                    <p>No asset data included in this snapshot</p>
                                </div>
                            )}
                        </TabsContent>

                        <TabsContent value="crypto" className="space-y-6">
                            <div className="bg-gradient-to-br from-green-50 to-blue-50 dark:from-green-950 dark:to-blue-950 p-4 rounded-lg border border-green-200 dark:border-green-800">
                                <div className="flex items-center gap-2 mb-2">
                                    <Shield className="h-5 w-5 text-green-600" />
                                    <h3 className="font-semibold text-green-900 dark:text-green-100">
                                        Cryptographic Chain of Trust
                                    </h3>
                                </div>
                                <p className="text-xs text-green-700 dark:text-green-300">
                                    This snapshot is part of an immutable cryptographic chain. The hashes below can be independently verified.
                                </p>
                            </div>

                            <CryptoField
                                label="Content Hash (SHA-256)"
                                value={data.content_hash}
                            />

                            <CryptoField
                                label="Signature Hash"
                                value={data.signature_hash}
                            />

                            {data.previous_snapshot_id && (
                                <CryptoField
                                    label="Previous Snapshot ID (Chain Link)"
                                    value={data.previous_snapshot_id}
                                    link={`#`} // Would navigate to previous snapshot in real implementation
                                />
                            )}

                            <div className="mt-6 p-4 border rounded-lg bg-muted/50">
                                <h4 className="text-sm font-medium mb-2">Verification Instructions</h4>
                                <ol className="text-xs text-muted-foreground space-y-1 list-decimal list-inside">
                                    <li>Download the verification SDK from /docs/energy/verification</li>
                                    <li>Export the full snapshot chain via the Export button</li>
                                    <li>Run: <code className="bg-muted px-1 py-0.5 rounded">verify-chain --snapshot-id {data.id.slice(0, 8)}</code></li>
                                    <li>Verify that content hash matches recomputed hash</li>
                                </ol>
                            </div>
                        </TabsContent>
                    </Tabs>
                ) : (
                    <div className="text-center py-12 text-muted-foreground">
                        <p>Failed to load snapshot details</p>
                    </div>
                )}
            </DialogContent>
        </Dialog>
    );
}
