/**
 * Snapshot Card Component
 * 
 * READ-ONLY display of individual snapshot.
 * 
 * Rules:
 * - Displays backend data verbatim (no derivation)
 * - Shows verification state at render time
 * - No actions (read-only)
 * - Links to detail view only
 */

import { useState } from 'react';
import { useSnapshotDetail } from '../api/queries/useSnapshots';
import { VerificationIndicator } from './VerificationIndicator';
import type { ComplianceSnapshot } from '../types/energy.types';

interface SnapshotCardProps {
    snapshot: ComplianceSnapshot;
    substationId: string;
}

export const SnapshotCard = ({ snapshot, substationId }: SnapshotCardProps) => {
    const [expanded, setExpanded] = useState(false);

    // Only load details when expanded
    const { data: detailData, isLoading: detailLoading } = useSnapshotDetail(
        expanded ? snapshot.id : null,
        {
            includeAssetDetails: expanded,
            includeEspConfig: false // Heavy field, not needed for card view
        }
    );

    // Status color mapping (reflects backend, doesn't derive)
    const statusColors = {
        NOMINAL: 'bg-green-100 text-green-800 border-green-200',
        DEGRADED: 'bg-amber-100 text-amber-800 border-amber-200',
        NON_COMPLIANT: 'bg-red-100 text-red-800 border-red-200'
    };

    const statusColor = statusColors[snapshot.system_status];

    return (
        <div className="relative pl-16">
            {/* Timeline dot */}
            <div className="absolute left-[1.875rem] top-6 h-3 w-3 rounded-full border-2 border-gray-300 bg-white" />

            {/* Card */}
            <div className="rounded-lg border border-gray-200 bg-white shadow-sm hover:shadow-md transition-shadow">
                {/* Header */}
                <div className="flex items-start justify-between p-4">
                    <div className="flex-1">
                        {/* Timestamp */}
                        <div className="text-sm text-gray-500">
                            {new Date(snapshot.snapshot_time).toLocaleString('en-US', {
                                dateStyle: 'medium',
                                timeStyle: 'short'
                            })}
                        </div>

                        {/* Status badge */}
                        <div className="mt-2 flex items-center gap-2">
                            <span className={`inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-medium ${statusColor}`}>
                                {snapshot.system_status}
                            </span>

                            {/* Trigger event */}
                            {snapshot.trigger_event && (
                                <span className="text-xs text-gray-500">
                                    {snapshot.trigger_event.replace(/_/g, ' ')}
                                </span>
                            )}
                        </div>

                        {/* Generated by */}
                        <div className="mt-1 text-xs text-gray-500">
                            Generated by {snapshot.generated_by.toLowerCase().replace(/_/g, ' ')}
                        </div>
                    </div>

                    {/* Verification indicator */}
                    <VerificationIndicator
                        substationId={substationId}
                        snapshotId={snapshot.id}
                    />
                </div>

                {/* Expandable details */}
                <div className="border-t border-gray-100 px-4 py-3">
                    <button
                        onClick={() => setExpanded(!expanded)}
                        className="flex w-full items-center justify-between text-sm font-medium text-gray-700 hover:text-gray-900"
                    >
                        <span>Snapshot Details</span>
                        <svg
                            className={`h-5 w-5 transition-transform ${expanded ? 'rotate-180' : ''}`}
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                    </button>

                    {expanded && (
                        <div className="mt-4 space-y-3 text-sm">
                            {detailLoading ? (
                                <div className="text-gray-500">Loading details...</div>
                            ) : (
                                <>
                                    {/* Snapshot ID */}
                                    <div>
                                        <div className="font-medium text-gray-900">Snapshot ID</div>
                                        <div className="mt-1 font-mono text-xs text-gray-600">{snapshot.id}</div>
                                    </div>

                                    {/* Content hash */}
                                    <div>
                                        <div className="font-medium text-gray-900">Content Hash</div>
                                        <div className="mt-1 font-mono text-xs text-gray-600 break-all">
                                            {snapshot.content_hash}
                                        </div>
                                    </div>

                                    {/* Signature hash */}
                                    <div>
                                        <div className="font-medium text-gray-900">Signature Hash</div>
                                        <div className="mt-1 font-mono text-xs text-gray-600 break-all">
                                            {snapshot.signature_hash}
                                        </div>
                                    </div>

                                    {/* Chain linkage */}
                                    {snapshot.previous_snapshot_id && (
                                        <div>
                                            <div className="font-medium text-gray-900">Previous Snapshot</div>
                                            <div className="mt-1 font-mono text-xs text-gray-600">
                                                {snapshot.previous_snapshot_id}
                                            </div>
                                        </div>
                                    )}

                                    {/* Asset summary (if loaded) */}
                                    {detailData?.asset_states?.summary && (
                                        <div>
                                            <div className="font-medium text-gray-900">Asset Summary</div>
                                            <div className="mt-1 grid grid-cols-2 gap-2 text-xs text-gray-600">
                                                <div>Total: {detailData.asset_states.summary.total_assets || 0}</div>
                                                <div>Verified: {detailData.asset_states.summary.verified_count || 0}</div>
                                                <div>Mismatches: {detailData.asset_states.summary.mismatch_count || 0}</div>
                                                <div>Unknown: {detailData.asset_states.summary.unknown_count || 0}</div>
                                            </div>
                                        </div>
                                    )}
                                </>
                            )}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};
