/**
 * FDA Food Traceability List (FTL) category data.
 *
 * Shared between the full FTL Checker tool and the onboarding quick-check.
 * Source: 21 CFR Part 1, Subpart S — FDA Food Traceability Rule (FSMA 204)
 */

export interface FTLCategory {
  id: string;
  name: string;
  category: 'Produce' | 'Seafood' | 'Dairy' | 'Eggs' | 'Other';
  examples: string;
  exclusions?: string;
  covered: boolean;
  outbreakFrequency: 'HIGH' | 'MODERATE' | 'N/A';
  ctes: string[];
  cfrSections: string;
  kdes: string[];
}

export const FTL_CATEGORIES: FTLCategory[] = [
  {
    id: 'leafy-greens-fresh',
    name: 'Leafy Greens (fresh, intact)',
    category: 'Produce',
    examples: 'Whole leaf lettuce, spinach bunches, kale, arugula, chard, collard greens',
    exclusions: 'Does not include whole head cabbages (green, red, savoy) or banana/grape/tree leaves. See fresh-cut leafy greens for pre-cut/bagged products.',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'leafy-greens-fresh-cut',
    name: 'Leafy Greens (fresh-cut)',
    category: 'Produce',
    examples: 'Bagged salad mix, spring mix, pre-washed spinach, chopped romaine, salad kits',
    exclusions: 'Does not include dried or frozen leafy greens',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    category: 'Produce',
    examples: 'Fresh tomatoes (not canned or dried)',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'peppers',
    name: 'Peppers',
    category: 'Produce',
    examples: 'Bell peppers, jalapeños, chili peppers (fresh)',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'cucumbers',
    name: 'Cucumbers',
    category: 'Produce',
    examples: 'Fresh cucumbers',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'herbs',
    name: 'Fresh Herbs',
    category: 'Produce',
    examples: 'Cilantro, parsley, basil (fresh cut)',
    exclusions: 'Note: Herbs in 21 CFR 112.2(a)(1), such as dill, are exempt under §1.1305(e)',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'melons',
    name: 'Melons',
    category: 'Produce',
    examples: 'Cantaloupe, honeydew, watermelon',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Harvesting', 'Cooling', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Cooling Location Identifier', 'Field Identification'],
  },
  {
    id: 'tropical-fruits',
    name: 'Tropical Tree Fruits',
    category: 'Produce',
    examples: 'Mangoes, papayas, mamey, guava',
    exclusions: 'Does not include: bananas, pineapple, dates (non-tree); coconut (tree nut); avocado (pit fruit); or citrus',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Harvesting', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Field Identification'],
  },
  {
    id: 'sprouts',
    name: 'Sprouts',
    category: 'Produce',
    examples: 'Alfalfa, bean, broccoli sprouts',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Harvesting', 'Initial Packing', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1325, §1.1330, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Seed Source', 'Growing Location'],
  },
  {
    id: 'fresh-cut-fruits',
    name: 'Fresh-Cut Fruits',
    category: 'Produce',
    examples: 'Pre-cut fruit mixes, fruit cups',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'fresh-cut-vegetables',
    name: 'Fresh-Cut Vegetables (non-leafy)',
    category: 'Produce',
    examples: 'Veggie trays, pre-cut carrots, celery sticks, broccoli florets',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'finfish-histamine',
    name: 'Finfish — Scombrotoxin/Histamine-Forming',
    category: 'Seafood',
    examples: 'Tuna, mackerel, mahi-mahi, bluefish, amberjack, bonito',
    exclusions: 'Catfish (Siluriformes) are USDA-regulated and excluded per §1.1305(g)',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['First Land-Based Receiving', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1335, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Vessel Name', 'Harvest Area', 'Landing Port'],
  },
  {
    id: 'finfish-ciguatoxin',
    name: 'Finfish — Ciguatoxin-Associated',
    category: 'Seafood',
    examples: 'Barracuda, grouper, snapper, moray eel (tropical reef species)',
    exclusions: 'Catfish (Siluriformes) are USDA-regulated and excluded per §1.1305(g)',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['First Land-Based Receiving', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1335, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Vessel Name', 'Harvest Area', 'Landing Port'],
  },
  {
    id: 'finfish-other',
    name: 'Finfish — Other (fresh/frozen/previously frozen)',
    category: 'Seafood',
    examples: 'Salmon, cod, halibut, tilapia, trout, bass, swordfish',
    exclusions: 'Catfish (Siluriformes) are USDA-regulated and excluded per §1.1305(g)',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['First Land-Based Receiving', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1335, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Vessel Name', 'Harvest Area', 'Landing Port'],
  },
  {
    id: 'finfish-smoked',
    name: 'Smoked Finfish',
    category: 'Seafood',
    examples: 'Smoked salmon, lox, kippered herring, smoked trout, smoked whitefish',
    exclusions: 'Catfish (Siluriformes) are USDA-regulated and excluded per §1.1305(g)',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'crustaceans',
    name: 'Crustaceans',
    category: 'Seafood',
    examples: 'Shrimp, crab, lobster, crawfish',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['First Land-Based Receiving', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1335, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Harvest Area', 'Vessel or Container ID'],
  },
  {
    id: 'molluscan-shellfish',
    name: 'Molluscan Shellfish (bivalves)',
    category: 'Seafood',
    examples: 'Oysters, clams, mussels, scallops',
    exclusions: 'Except when product consists entirely of shucked adductor muscle. Raw bivalves under NSSP may be exempt per §1.1305(f)',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['First Land-Based Receiving', 'Shipping', 'Receiving', 'Transformation'],
    cfrSections: '§1.1335, §1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Harvest Area', 'Harvest Tag', 'NSSP Dealer Certificate'],
  },
  {
    id: 'deli-salads',
    name: 'Ready-to-Eat Deli Salads',
    category: 'Other',
    examples: 'Egg salad, seafood salad, pasta salad, potato salad',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'eggs',
    name: 'Shell Eggs',
    category: 'Eggs',
    examples: 'Whole shell eggs (chicken, duck)',
    exclusions: 'Farms with fewer than 3,000 laying hens are exempt per §1.1305(a)(2)',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Shipping', 'Receiving'],
    cfrSections: '§1.1340, §1.1345',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'TLC Source Location or Reference', 'Farm/Flock Identifier'],
  },
  {
    id: 'nut-butters',
    name: 'Nut Butters',
    category: 'Other',
    examples: 'Peanut butter, almond butter',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'cheese-fresh-soft',
    name: 'Fresh Soft Cheese',
    category: 'Dairy',
    examples: 'Queso fresco, ricotta, mascarpone, cream cheese, panela, boursin',
    exclusions: 'Hard cheeses per 21 CFR 133.150 (e.g., cheddar, parmesan, aged cotija) are excluded from the FTL. Cottage cheese is exempt (finalized April 2026; listed on IMS List, §1.1305(d)).',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'cheese-soft-ripened',
    name: 'Soft Ripened & Semi-Soft Cheese',
    category: 'Dairy',
    examples: 'Brie, camembert, monterey jack, muenster, gouda, havarti, oaxaca, feta',
    exclusions: 'Hard cheeses per 21 CFR 133.150 are excluded. Semi-soft classification per FDA guidance includes cheeses with moisture content >39%',
    covered: true,
    outbreakFrequency: 'MODERATE',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'cheese-unpasteurized',
    name: 'Cheese Made from Unpasteurized Milk (non-hard)',
    category: 'Dairy',
    examples: 'Raw-milk brie, raw-milk feta, raw-milk camembert, artisanal raw-milk soft cheeses',
    exclusions: 'Hard cheeses aged 60+ days per 21 CFR 133.150 are excluded even if made from unpasteurized milk',
    covered: true,
    outbreakFrequency: 'HIGH',
    ctes: ['Receiving', 'Transformation', 'Shipping'],
    cfrSections: '§1.1340, §1.1345, §1.1350',
    kdes: ['Traceability Lot Code (TLC)', 'Location Identifier (GLN)', 'Date/Time', 'Quantity & UOM', 'Product Description', 'Reference Document Type & Number', 'Input TLCs', 'New TLC Assigned'],
  },
  {
    id: 'canned-goods',
    name: 'Canned/Processed',
    category: 'Other',
    examples: 'Canned vegetables, frozen dinners, dried products',
    exclusions: 'Once food leaves fresh form (dried, frozen, canned), it is off the FTL',
    covered: false,
    outbreakFrequency: 'N/A',
    ctes: [],
    cfrSections: '',
    kdes: [],
  },
  {
    id: 'bakery',
    name: 'Bakery Products',
    category: 'Other',
    examples: 'Bread, pastries, cookies',
    covered: false,
    outbreakFrequency: 'N/A',
    ctes: [],
    cfrSections: '',
    kdes: [],
  },
  {
    id: 'beverages',
    name: 'Beverages',
    category: 'Other',
    examples: 'Juices, sodas, water',
    covered: false,
    outbreakFrequency: 'N/A',
    ctes: [],
    cfrSections: '',
    kdes: [],
  },
];

/** Only the categories that are on the FDA Food Traceability List */
export const FTL_COVERED_CATEGORIES = FTL_CATEGORIES.filter((c) => c.covered);

/** Group categories by their food group */
export const FTL_GROUPS = [...new Set(FTL_CATEGORIES.map((c) => c.category))];
